# Generated by Django 3.1.2 on 2020-11-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='maker',
        ),
    ]
